SELECT * FROM customerdata.customer_purchase_data;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender ,sum(purchase_amount) as revenue
from customerdata.customer_purchase_data
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select CustomerID, purchase_amount 
from customer_purchase_data
where Discount_Amount >=10 and Purchase_amount >=(select avg(Purchase_amount) from customer_purchase_data);

-- Q3. Which are the top 5 products with the highest average review rating?
select Item , round(avg(Review_Rate),2) as "as average product rating"
from customer_purchase_data
group by Item
order by avg(Review_Rate) desc
limit 5;

-- Q4. Compare the average purchase amount between Standard and Express shipping.
select Shipping_Type,
round(avg(Purchase_amount),2)
from  customer_purchase_data
where Shipping_Type in ('Standard' , 'Express')
group by Shipping_Type;

-- Q5. Do subscribed customers spend more?
-- Compare the average spend and total revenue between subscribers and non-subscribers.
select Subscription_Status,
Count(CustomerID) as total_customers,
round(avg(Purchase_amount),2) as avg_spend,
round(sum(Purchase_amount),2) as total_revenue
from customer_purchase_data
group by Subscription_Status
order by total_customers , avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select Item,
round(sum(case when Discount_amount >= 10 then 1 else 0 end) * 100 / count(*) ,2) as discount_rate
from customer_purchase_data
group by Item
order by Discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases.


SELECT
    CustomerID,
    SUM(PreviousPurchases) AS total_previous_purchases,
    CASE
        WHEN SUM(PreviousPurchases) <= 1 THEN 'New'
        WHEN SUM(PreviousPurchases) BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM customer_purchase_data
GROUP BY CustomerID
ORDER BY total_previous_purchases DESC;

-- Q8. What are the top 3 most purchased products within each category?


WITH product_count AS (
    SELECT
        Purchase_Category,
        Item,
        COUNT(*) AS total_purchases
    FROM customer_purchase_data
    GROUP BY Purchase_Category, Item
),

ranked_products AS (
    SELECT
        Purchase_Category,
        Item,
        total_purchases,
        DENSE_RANK() OVER (
            PARTITION BY Purchase_Category
            ORDER BY total_purchases DESC
        ) AS product_rank
    FROM product_count
)

SELECT
   Purchase_Category,
    Item,
    total_purchases,
    product_rank
FROM ranked_products
WHERE product_rank <= 3
ORDER BY Purchase_Category, product_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select Subscription_Status,
count(CustomerID) as repeat_buyers
from customer_purchase_data
where PreviousPurchases > 5
group by Subscription_Status;

-- Q10. What is the revenue contribution of each age group?

SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN 'Young Adult'
        WHEN Age BETWEEN 26 AND 45 THEN 'Middle Aged Adult'
        ELSE 'Senior'
    END AS age_group,

    SUM(Purchase_Amount) AS total_revenue

FROM customer_purchase_data

GROUP BY
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN 'Young Adult'
        WHEN Age BETWEEN 26 AND 45 THEN 'Middle Aged Adult'
        ELSE 'Senior'
    END

ORDER BY total_revenue DESC;